#!/usr/bin/env bash

CFGSDIR="$(dirname "$0")"
MYDIR="$(realpath "$(dirname "$0")/../..")"
DEVDIR="$(realpath "$(dirname "$0")/..")"
BINDIR="$DEVDIR/bin"

echo "#!/usr/bin/env bash" > "$HOME/.setdirs"
echo "export MYDIR=\"$MYDIR\"" >> "$HOME/.setdirs"
echo "export DEVDIR=\"$DEVDIR\"" >> "$HOME/.setdirs"

mkdir "$BINDIR" > /dev/null 2> /dev/null
mkdir "$DEVDIR/tmp" > /dev/null 2> /dev/null
mkdir "$DEVDIR/archive" > /dev/null 2> /dev/null

mkdir "$MYDIR/tmp" > /dev/null 2> /dev/null
mkdir "$MYDIR/reading" > /dev/null 2> /dev/null
mkdir "$MYDIR/reading/Calibre Library" > /dev/null 2> /dev/null

cp "$CFGSDIR/vscin" "$BINDIR/vscin"
chmod +x "$BINDIR/vscin"

cp "$CFGSDIR/runemacs" "$BINDIR/runemacs"
chmod +x "$BINDIR/runemacs"

cp "$CFGSDIR/juplab" "$BINDIR/juplab"
chmod +x "$BINDIR/juplab"

cp "$CFGSDIR/venvin" "$BINDIR/venvin"

cp "$CFGSDIR/.bash_profile" "$HOME/.bash_profile"

mkdir "$HOME/.config" > /dev/null 2> /dev/null
mkdir "$HOME/.config/nvim" > /dev/null 2> /dev/null
cp "$CFGSDIR/init.vim" "$HOME/.config/nvim/init.vim"

mkdir "$HOME/.emacs.d" > /dev/null 2> /dev/null
mkdir "$HOME/.emacs.d/backups" > /dev/null 2> /dev/null
mkdir "$HOME/.emacs.d/autosaves" > /dev/null 2> /dev/null
cat /dev/null > "$HOME/.emacs.d/custom.el"
cp "$CFGSDIR/init.el" "$HOME/.emacs.d/init.el"

cp "$CFGSDIR/.gitconfig" "$HOME/.gitconfig"

rm -r "$HOME/Music/my_music" > /dev/null 2> /dev/null
cp -r "$MYDIR/g/music" "$HOME/Music/my_music"

if [ "$(uname)" = "Darwin" ] ; then
    if [ "$1" = "--install" ] ; then
        if [ "$(uname -m)" = "arm64" ] && ! (arch -arch x86_64 uname -m > /dev/null) ; then
            softwareupdate --install-rosetta --agree-to-license > /dev/null
        fi

        eval $(/opt/homebrew/bin/brew shellenv)
        brew bundle install --no-upgrade --file="$CFGSDIR/Brewfile" > /dev/null

        python3 -m venv "$DEVDIR/.venv"

        . "$CFGSDIR/.bash_profile"

        # pip install --requirement "$CFGSDIR/requirements.txt"
    fi
fi

