#!/usr/bin/env bash

CFGSDIR="$(realpath "$(dirname "$0")")"
MYDIR="$(realpath "$CFGSDIR/../..")"
DEVDIR="$(realpath "$CFGSDIR/..")"
BINDIR="$DEVDIR/bin"

echo "#!/usr/bin/env bash" > "$HOME/.setdirs"
echo "export MYDIR=\"$MYDIR\"" >> "$HOME/.setdirs"
echo "export DEVDIR=\"$DEVDIR\"" >> "$HOME/.setdirs"
echo "export CFGSDIR=\"$CFGSDIR\"" >> "$HOME/.setdirs"
echo "export BINDIR=\"$BINDIR\"" >> "$HOME/.setdirs"

mkdir "$BINDIR" > /dev/null 2> /dev/null
mkdir "$DEVDIR/tmp" > /dev/null 2> /dev/null
mkdir "$DEVDIR/archive" > /dev/null 2> /dev/null

mkdir "$MYDIR/tmp" > /dev/null 2> /dev/null
mkdir "$MYDIR/reading" > /dev/null 2> /dev/null
mkdir "$MYDIR/reading/Calibre Library" > /dev/null 2> /dev/null

cp "$CFGSDIR/vscin" "$BINDIR/vscin"
chmod +x "$BINDIR/vscin"

cp "$CFGSDIR/runemacs" "$BINDIR/runemacs"
chmod +x "$BINDIR/runemacs"

cp "$CFGSDIR/juplab" "$BINDIR/juplab"
chmod +x "$BINDIR/juplab"

cp "$CFGSDIR/terminal" "$BINDIR/terminal"
chmod +x "$BINDIR/terminal"

cp "$CFGSDIR/venvin" "$BINDIR/venvin"

cp "$CFGSDIR/.bash_profile" "$HOME/.bash_profile"

mkdir "$HOME/.config" > /dev/null 2> /dev/null
mkdir "$HOME/.config/nvim" > /dev/null 2> /dev/null
cp "$CFGSDIR/init.vim" "$HOME/.config/nvim/init.vim"

mkdir "$HOME/.emacs.d" > /dev/null 2> /dev/null
mkdir "$HOME/.emacs.d/backups" > /dev/null 2> /dev/null
mkdir "$HOME/.emacs.d/autosaves" > /dev/null 2> /dev/null
cat /dev/null > "$HOME/.emacs.d/custom.el"
cp "$CFGSDIR/init.el" "$HOME/.emacs.d/init.el"

cp "$CFGSDIR/.gitconfig" "$HOME/.gitconfig"

if [ "$1" = "--install" ] ; then
    "$BINDIR/terminal" "$CFGSDIR/install"
fi

. "$CFGSDIR/envin"

# can now do anything, it's like we just started a typical shell.

# soon we will automate getting "$MYDIR/g"
rm -r "$HOME/Music/my_music" > /dev/null 2> /dev/null
cp -r "$MYDIR/g/music" "$HOME/Music/my_music"

