#!/usr/bin/env bash

eval "$(/opt/homebrew/bin/brew shellenv)"

export PATH="$BINDIR:$PATH"

. "$DEVDIR/.venv/bin/activate"
export PS1=$_OLD_VIRTUAL_PS1

export BASH_SILENCE_DEPRECATION_WARNING=1

export SHIN=1
