#!/usr/bin/env bash

if [ ! -d "$MYDIR/tmp/drive_downloads" ] ; then
    mkdir "$MYDIR/tmp/drive_downloads"
fi

if ls "$HOME/Downloads/g-"* > /dev/null 2> /dev/null ; then
    pushd "$MYDIR/tmp/drive_downloads" > /dev/null
    rm -f *
    mv -f "$HOME/Downloads/g-"* .
    rm -rf "$MYDIR/g"
    unzip '*.zip' -d "$MYDIR"
    popd > /dev/null
else
    echo "error: no drive files found in \"$HOME/Downloads\""
fi

