#!/usr/bin/env bash

if [ -f "$1" ] ; then
    FILEPATH="$(realpath "$1")"
else
    FILEPATH="$(which "$1")"
fi


if [ -z "$FILEPATH" ] ; then
    COMMAND="cd '$PWD'"
else
    shift 1
    COMMAND="cd '$PWD' && '$FILEPATH' $* && exit"
fi

osascript -e 'tell app "Terminal" to activate' -e "tell app \"Terminal\" to do script \"$COMMAND\"" > /dev/null

unset COMMAND
