#!/usr/bin/env bash

if [ -f "$1" ] ; then
    FILEPATH="$(realpath "$1")"
else
    FILEPATH="$(which "$1")"
fi

if [ -z "$FILEPATH" ] ; then
    osascript "$CFGSDIR/terminal.scpt" > /dev/null
else
    shift 1
    osascript "$CFGSDIR/terminal.scpt" "$FILEPATH" "$@" > /dev/null
fi

