#!/usr/bin/env bash

if [ -z "$*" ] ; then
    script="cd '$PWD'"
else
    printf -v script "'%s' " "$@"
    script="${script% }"
    script="cd '$PWD' && $script && exit"
fi

osascript -e 'tell app "Terminal" to activate' -e "tell app \"Terminal\" to do script \"$script\"" > /dev/null

