#!/usr/bin/env bash

mkdir .vscode > /dev/null 2> /dev/null
pushd .vscode > /dev/null
if [ -e settings.json ] ; then
    echo "error: settings.json already exists" >&2
else
    cp "$CFGSDIR/settings.json" settings.json
fi
popd > /dev/null

